/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import dao.CouponDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Coupon;

/**
 *
 * @author apiksha
 */
public class AddCoupon extends javax.swing.JFrame {

    /**
     * Creates new form addCoupon
     */
    public String id;
    public AddCoupon() {
        initComponents();
        btnsave.setEnabled(false);
    }
      public AddCoupon(String id) {
        initComponents();
        this.id=id;
        btnsave.setEnabled(false);
    }
      
    public void showCoupon(){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Coupon> coupons = CouponDao.getAllCuppon();
        
        int rc=dtm.getRowCount();
        for(int i=0;i<rc;i++){
            dtm.removeRow(0);
        }
        
        Iterator<Coupon> itr = coupons.iterator();
        while(itr.hasNext()){
            Coupon c=itr.next();
            
            dtm.addRow(new Object[]{c.getId(),c.getAmount()});
        }
        
    }

    public void validateFields()
    {
        String couponid=txtcouponcode.getText();
        
        String price=txtdiscount.getText();
        if(!couponid.equals("")&& !price.equals("")){
            btnsave.setEnabled(true);
        }
        else{
            btnsave.setEnabled(false);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        txtcouponcode = new javax.swing.JTextField();
        txtdiscount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mback = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coupns.jpeg"))); // NOI18N
        jLabel1.setText("ADD NEW COUPONS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 37, 750, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Coupon Code :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 271, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Discount Amount :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 311, -1, -1));

        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(204, 0, 51));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 396, 111, -1));

        btncancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(204, 0, 51));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 396, 111, -1));

        txtcouponcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcouponcodeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtcouponcodeMouseReleased(evt);
            }
        });
        txtcouponcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcouponcodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcouponcodeKeyReleased(evt);
            }
        });
        getContentPane().add(txtcouponcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 271, 282, -1));

        txtdiscount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtdiscountMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtdiscountMouseReleased(evt);
            }
        });
        txtdiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiscountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdiscountKeyReleased(evt);
            }
        });
        getContentPane().add(txtdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 309, 282, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Coupon ID", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 360, 210));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("* click on row to delete coupon");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backg.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setForeground(new java.awt.Color(204, 0, 0));
        jMenu1.setText("<-");
        jMenu1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jMenu1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N

        mback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mback.setForeground(new java.awt.Color(255, 153, 0));
        mback.setText("Back");
        mback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbackActionPerformed(evt);
            }
        });
        jMenu1.add(mback);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbackActionPerformed
        // TODO add your handling code here:
        AdminPage hForm = new AdminPage(id);
                hForm.setVisible(true);
                dispose();
    }//GEN-LAST:event_mbackActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
         Coupon i= new Coupon();
         i.setId(txtcouponcode.getText());
        
        i.setAmount(txtdiscount.getText());

        
        CouponDao.save(i);
        JOptionPane.showMessageDialog(null,"Coupon Added Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
        txtcouponcode.setText("");
       
        txtdiscount.setText("");
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
         txtcouponcode.setText("");
       
        txtdiscount.setText("");
    }//GEN-LAST:event_btncancelActionPerformed

    private void txtcouponcodeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcouponcodeMousePressed
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtcouponcodeMousePressed

    private void txtcouponcodeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcouponcodeMouseReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtcouponcodeMouseReleased

    private void txtdiscountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiscountMousePressed
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtdiscountMousePressed

    private void txtdiscountMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiscountMouseReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtdiscountMouseReleased

    private void txtcouponcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcouponcodeKeyPressed
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtcouponcodeKeyPressed

    private void txtcouponcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcouponcodeKeyReleased
        // TODO add your handling code here:validateFields();
        validateFields();
    }//GEN-LAST:event_txtcouponcodeKeyReleased

    private void txtdiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscountKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtdiscountKeyReleased

    private void txtdiscountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscountKeyPressed
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtdiscountKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        showCoupon();
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int ind = jTable1.getSelectedRow();
        String id = jTable1.getValueAt(ind, 0).toString();
        int a =JOptionPane.showConfirmDialog(null,"Do you really want to delete this coupon ?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
           CouponDao.delete(id);
           showCoupon();
        
         
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCoupon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCoupon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem mback;
    private javax.swing.JTextField txtcouponcode;
    private javax.swing.JTextField txtdiscount;
    // End of variables declaration//GEN-END:variables
}
