/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import dao.ItemDao;
import javax.swing.JOptionPane;
import model.Item;

/**
 *
 * @author apiksha
 */
public class AddItem extends javax.swing.JFrame {

    /**
     * Creates new form AddItem
     */
    public String id;
    public AddItem() {
        initComponents();
        btnsave.setEnabled(false);
    }
      public AddItem(String id) {
        initComponents();
        this.id=id;
        btnsave.setEnabled(false);
    }

    public void validateFields()
    {
        String id=txtitemid.getText();
        String name=txtitemname.getText();
        String price=txtitemprice.getText();
        if(!id.equals("")&& !price.equals("")&&!name.equals("")){
            btnsave.setEnabled(true);
        }
        else{
            btnsave.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtitemname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtitemprice = new javax.swing.JTextField();
        txtcategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtitemid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mback = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        jLabel1.setText("ADD ITEMS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 97, 300, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 274, -1, -1));

        txtitemname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtitemnameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtitemnameMouseReleased(evt);
            }
        });
        txtitemname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitemnameActionPerformed(evt);
            }
        });
        txtitemname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtitemnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtitemnameKeyReleased(evt);
            }
        });
        getContentPane().add(txtitemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 272, 304, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item Price :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 312, -1, -1));

        txtitemprice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtitempriceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtitempriceMouseReleased(evt);
            }
        });
        txtitemprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitempriceActionPerformed(evt);
            }
        });
        txtitemprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtitempriceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtitempriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtitemprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 312, 304, -1));

        txtcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drinks", "Snacks", "Combos" }));
        txtcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(txtcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 352, 304, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category  :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 352, -1, -1));

        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(204, 0, 102));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 481, 98, -1));

        btncancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(204, 0, 102));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 481, 97, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Item Id :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        txtitemid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtitemidMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtitemidMouseReleased(evt);
            }
        });
        txtitemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtitemidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtitemidKeyReleased(evt);
            }
        });
        getContentPane().add(txtitemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 300, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgrd.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        jMenu1.setText("<-");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        mback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mback.setForeground(new java.awt.Color(255, 153, 0));
        mback.setText("Back");
        mback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbackActionPerformed(evt);
            }
        });
        jMenu1.add(mback);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtitemnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitemnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtitemnameActionPerformed

    private void txtitempriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitempriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtitempriceActionPerformed

    private void txtcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcategoryActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtcategoryActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
         Item i= new Item();
         i.setId(txtitemid.getText());
        i.setName(txtitemname.getText());
        i.setPrice(txtitemprice.getText());
        i.setCategory((String)txtcategory.getSelectedItem());
        
        ItemDao.save(i);
        JOptionPane.showMessageDialog(null,"Item Added Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
        txtitemid.setText("");
        txtitemname.setText("");
        txtitemprice.setText("");
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
         Item i= new Item();
         txtitemid.setText("");
        txtitemname.setText("");
        txtitemprice.setText("");
    }//GEN-LAST:event_btncancelActionPerformed

    private void mbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbackActionPerformed
        // TODO add your handling code here:
        AdminPage hForm = new AdminPage(id);
                hForm.setVisible(true);
                dispose();
    }//GEN-LAST:event_mbackActionPerformed

    private void txtitemidMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtitemidMousePressed
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtitemidMousePressed

    private void txtitemidMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtitemidMouseReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtitemidMouseReleased

    private void txtitemnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtitemnameMousePressed
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtitemnameMousePressed

    private void txtitemnameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtitemnameMouseReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtitemnameMouseReleased

    private void txtitempriceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtitempriceMousePressed
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtitempriceMousePressed

    private void txtitempriceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtitempriceMouseReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtitempriceMouseReleased

    private void txtitempriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitempriceKeyPressed
        // TODO add your handling code here:
         validateFields();
    }//GEN-LAST:event_txtitempriceKeyPressed

    private void txtitemnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemnameKeyPressed
        // TODO add your handling code here:
         validateFields();
    }//GEN-LAST:event_txtitemnameKeyPressed

    private void txtitemidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemidKeyPressed
        // TODO add your handling code here:
         validateFields();
    }//GEN-LAST:event_txtitemidKeyPressed

    private void txtitemidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemidKeyReleased
        // TODO add your handling code here:
         validateFields();
    }//GEN-LAST:event_txtitemidKeyReleased

    private void txtitemnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemnameKeyReleased
        // TODO add your handling code here:
         validateFields();
    }//GEN-LAST:event_txtitemnameKeyReleased

    private void txtitempriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitempriceKeyReleased
        // TODO add your handling code here:
         validateFields();
    }//GEN-LAST:event_txtitempriceKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mback;
    private javax.swing.JComboBox<String> txtcategory;
    private javax.swing.JTextField txtitemid;
    private javax.swing.JTextField txtitemname;
    private javax.swing.JTextField txtitemprice;
    // End of variables declaration//GEN-END:variables
}
