/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import dao.ItemDao;
import dao.OfferDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Item;
import model.Offer;

/**
 *
 * @author apiksha
 */
public class AddOffer extends javax.swing.JFrame {

    /**
     * Creates new form AddOffer
     */
    public String id;
    public AddOffer() {
        initComponents();
    }
      public AddOffer(String id) {
        initComponents();
        this.id=id;
        btnsave.setEnabled(false);
    }

    public void validateFields()
    {
        String id=txtofferid.getText();
        String percent=txtdiscount.getText();
        
        if(!id.equals("")&& !percent.equals("")){
            btnsave.setEnabled(true);
        }
        else{
            btnsave.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtofferid = new javax.swing.JTextField();
        txtdiscount = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        txtstatus = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        toffer = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mback = new javax.swing.JMenuItem();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        jLabel1.setText("ADD NEW OFFER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 440, 81));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Offer Id :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Discount Percent :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Status :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        txtofferid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtofferidMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtofferidMouseReleased(evt);
            }
        });
        txtofferid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtofferidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtofferidKeyReleased(evt);
            }
        });
        getContentPane().add(txtofferid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 359, -1));

        txtdiscount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtdiscountMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtdiscountMouseReleased(evt);
            }
        });
        txtdiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiscountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdiscountKeyReleased(evt);
            }
        });
        getContentPane().add(txtdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 359, -1));

        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(204, 0, 0));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 98, -1));

        btncancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(204, 0, 51));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 98, -1));

        txtstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        txtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatusActionPerformed(evt);
            }
        });
        getContentPane().add(txtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 359, -1));

        toffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "percent", "status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        toffer.getTableHeader().setReorderingAllowed(false);
        toffer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tofferMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(toffer);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 169, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgrd.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("^");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        mback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mback.setForeground(new java.awt.Color(255, 153, 0));
        mback.setText("Back");
        mback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbackActionPerformed(evt);
            }
        });
        jMenu1.add(mback);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbackActionPerformed
        // TODO add your handling code here:
        AdminPage hForm = new AdminPage(id);
                hForm.setVisible(true);
                dispose();
    }//GEN-LAST:event_mbackActionPerformed

    private void txtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatusActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        Offer o= new Offer();
         o.setId(txtofferid.getText());
        o.setPercent(txtdiscount.getText());
        o.setStatus((String)txtstatus.getSelectedItem());
        
        OfferDao.save(o);
        JOptionPane.showMessageDialog(null,"Offer Added Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
       
        txtofferid.setText("");
        txtdiscount.setText("");
        DefaultTableModel dtmS = (DefaultTableModel) toffer.getModel();
        ArrayList<Offer> itemS = OfferDao.getAllOffers();
        Iterator<Offer> itrS = itemS.iterator();
        int j=dtmS.getRowCount();
        for(int i=0;i<j;i++){
          dtmS.removeRow(0);
        }
         while(itrS.hasNext()){
            Offer oe = itrS.next();
            dtmS.addRow(new Object[]{oe.getId(),oe.getPercent(),oe.getStatus()});
         }  
        
         
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        txtofferid.setText("");
        txtdiscount.setText("");
    }//GEN-LAST:event_btncancelActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtmS = (DefaultTableModel) toffer.getModel();
        ArrayList<Offer> itemS = OfferDao.getAllOffers();
        Iterator<Offer> itrS = itemS.iterator();
         while(itrS.hasNext()){
            Offer o = itrS.next();
            dtmS.addRow(new Object[]{o.getId(),o.getPercent(),o.getStatus()});
            
        }
    }//GEN-LAST:event_formComponentShown

    private void txtofferidMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtofferidMousePressed
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtofferidMousePressed

    private void txtofferidMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtofferidMouseReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtofferidMouseReleased

    private void txtdiscountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiscountMousePressed
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtdiscountMousePressed

    private void txtdiscountMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiscountMouseReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtdiscountMouseReleased

    private void tofferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tofferMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtmS = (DefaultTableModel) toffer.getModel();
        int row=toffer.rowAtPoint(evt.getPoint());
        int col=toffer.columnAtPoint(evt.getPoint());
        String idrow=(String) dtmS.getValueAt(row,0);
        if(col==2)
        {
            String curr=(String) dtmS.getValueAt(row, col);
            String newv=curr.equals("False")?"True":"False";
           
            dtmS.setValueAt(newv, row, col);
            OfferDao.updatestatus(idrow,newv);
        }
        
    }//GEN-LAST:event_tofferMouseClicked

    private void txtofferidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtofferidKeyPressed
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtofferidKeyPressed

    private void txtofferidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtofferidKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtofferidKeyReleased

    private void txtdiscountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscountKeyPressed
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtdiscountKeyPressed

    private void txtdiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscountKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtdiscountKeyReleased
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOffer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mback;
    private javax.swing.JTable toffer;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtofferid;
    private javax.swing.JComboBox<String> txtstatus;
    // End of variables declaration//GEN-END:variables
}
