/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import dao.AdminDao;
import javax.swing.JOptionPane;

/**
 *
 * @author apiksha
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public String id;
    public AdminPage() {
        initComponents();
    }
   
     public AdminPage(String id) {
        initComponents();
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnnewadmin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnadditem = new javax.swing.JButton();
        btnaddcoupon = new javax.swing.JButton();
        btnoffer = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnorderhistory = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 204, 51));
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 214, 134));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout.setBackground(new java.awt.Color(180, 151, 205));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 165, 152, -1));

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Hi Admin!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 107, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("ADMIN PAGE");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 17, -1, -1));

        btnnewadmin.setBackground(new java.awt.Color(180, 151, 205));
        btnnewadmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnnewadmin.setText("Add new admin");
        btnnewadmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnnewadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewadminActionPerformed(evt);
            }
        });
        jPanel1.add(btnnewadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 165, 152, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 0, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 219, 788, 10));

        btnadditem.setBackground(new java.awt.Color(180, 151, 205));
        btnadditem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnadditem.setText("View/Add items");
        btnadditem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnadditem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadditemActionPerformed(evt);
            }
        });
        jPanel1.add(btnadditem, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 247, 147, 40));

        btnaddcoupon.setBackground(new java.awt.Color(180, 151, 205));
        btnaddcoupon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnaddcoupon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coupon.jpg"))); // NOI18N
        btnaddcoupon.setText("Add new coupon");
        btnaddcoupon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnaddcoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcouponActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddcoupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 305, 251, 38));

        btnoffer.setBackground(new java.awt.Color(180, 151, 205));
        btnoffer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnoffer.setText("Add new offer");
        btnoffer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnoffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnofferActionPerformed(evt);
            }
        });
        jPanel1.add(btnoffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 361, 147, 38));

        jSeparator2.setBackground(new java.awt.Color(102, 0, 153));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 428, 788, 12));

        btnorderhistory.setBackground(new java.awt.Color(180, 151, 205));
        btnorderhistory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnorderhistory.setText("View Order History");
        btnorderhistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnorderhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderhistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnorderhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 477, 243, 39));

        btndelete.setBackground(new java.awt.Color(180, 151, 205));
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndelete.setText("DELETE ADMIN");
        btndelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 790, 580));

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgrd.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 2610, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnorderhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderhistoryActionPerformed
        // TODO add your handling code here:
        AdminOrderTable oForm = new  AdminOrderTable(id);
                oForm.setVisible(true);
                dispose();
    }//GEN-LAST:event_btnorderhistoryActionPerformed

    private void btnofferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnofferActionPerformed
        // TODO add your handling code here:
        AddOffer oForm = new AddOffer(id);
                oForm.setVisible(true);
                dispose();
    }//GEN-LAST:event_btnofferActionPerformed

    private void btnaddcouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcouponActionPerformed
        // TODO add your handling code here:
        AddCoupon oForm = new AddCoupon(id);
                oForm.setVisible(true);
                dispose();
    }//GEN-LAST:event_btnaddcouponActionPerformed

    private void btnadditemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadditemActionPerformed
        // TODO add your handling code here:
        ItemTable oForm = new ItemTable(id);
                oForm.setVisible(true);
                dispose();
    }//GEN-LAST:event_btnadditemActionPerformed

    private void btnnewadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewadminActionPerformed
        // TODO add your handling code here:
        NewAdmin oForm = new NewAdmin(id);
                oForm.setVisible(true);
                dispose();
    }//GEN-LAST:event_btnnewadminActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        Admin_Login oForm = new Admin_Login();
                oForm.setVisible(true);
                dispose();
        
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        new DeleteAdmin( id).setVisible(true);
        dispose();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        if(AdminDao.getsuperadmin(id)){
            btndelete.setVisible(true);
        }else{
            btndelete.setVisible(false);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddcoupon;
    private javax.swing.JButton btnadditem;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnnewadmin;
    private javax.swing.JButton btnoffer;
    private javax.swing.JButton btnorderhistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
