/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import dao.OrderDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Order;

/**
 *
 * @author apiksha
 */
public class AdminOrderTable extends javax.swing.JFrame {

    /**
     * Creates new form adminOrderTable
     */
    public String id;
    public AdminOrderTable() {
        initComponents();
    }
      public AdminOrderTable(String id) {
        initComponents();
        this.id=id;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        torders = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tinfo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nback = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        torders.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        torders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Order ID", "Item Name", "Price", "Qty", "User Email", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        torders.getTableHeader().setReorderingAllowed(false);
        torders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tordersMouseClicked(evt);
            }
        });
        torders.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tordersComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(torders);
        if (torders.getColumnModel().getColumnCount() > 0) {
            torders.getColumnModel().getColumn(0).setMinWidth(40);
            torders.getColumnModel().getColumn(0).setPreferredWidth(40);
            torders.getColumnModel().getColumn(0).setMaxWidth(40);
            torders.getColumnModel().getColumn(2).setMinWidth(200);
            torders.getColumnModel().getColumn(2).setPreferredWidth(200);
            torders.getColumnModel().getColumn(2).setMaxWidth(200);
            torders.getColumnModel().getColumn(5).setMinWidth(200);
            torders.getColumnModel().getColumn(5).setPreferredWidth(200);
            torders.getColumnModel().getColumn(5).setMaxWidth(200);
            torders.getColumnModel().getColumn(6).setMinWidth(150);
            torders.getColumnModel().getColumn(6).setPreferredWidth(150);
            torders.getColumnModel().getColumn(6).setMaxWidth(150);
            torders.getColumnModel().getColumn(7).setMinWidth(150);
            torders.getColumnModel().getColumn(7).setPreferredWidth(150);
            torders.getColumnModel().getColumn(7).setMaxWidth(150);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 910, 419));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("CUSTOMER ORDERS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        tinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Total sum", "Offer", "Coupon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tinfo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 338, 419));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backg.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("<-");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        nback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nback.setForeground(new java.awt.Color(255, 153, 0));
        nback.setText("Back");
        nback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbackActionPerformed(evt);
            }
        });
        jMenu1.add(nback);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbackActionPerformed
        // TODO add your handling code here:
        AdminPage hForm = new AdminPage(id);
                hForm.setVisible(true);
                dispose();
    }//GEN-LAST:event_nbackActionPerformed

    private void tordersComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tordersComponentShown
        // TODO add your handling code here:
      
    }//GEN-LAST:event_tordersComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        int i=1;
        DefaultTableModel dtmS = (DefaultTableModel) torders.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tinfo.getModel();
        ArrayList<Order> itemS = OrderDao.getAllorders();
        Iterator<Order> itrS = itemS.iterator();
        String lid="";
         while(itrS.hasNext()){
            Order o = itrS.next();
            dtmS.addRow(new Object[]{i,o.getOrder_id(),o.getItem_name(),o.getPrice(),o.getQuantity(),o.getEmail(),o.getDate(),o.getStatus()});
             i++;
             
             if(!o.getOrder_id().equals(lid)){
                 lid=o.getOrder_id();
                 dtm.addRow(new Object[]{o.getOrder_id(),o.getTotalsum(),o.getOfferid(),o.getCupponid()});
             }
         
         }
        
        
    }//GEN-LAST:event_formComponentShown

    private void tordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tordersMouseClicked
        // TODO add your handling code here:
        TableModel tm =torders.getModel();
        int ind = torders.getSelectedRow();
        
        String id = tm.getValueAt(ind, 1).toString();
        String name = tm.getValueAt(ind, 2).toString();
        int opt=JOptionPane.showConfirmDialog(null, "Change status ?", "SELECT", JOptionPane.YES_NO_OPTION);
        
        if(opt==0){
            OrderDao.changeStatus(id,name);
            
            JOptionPane.showMessageDialog(null, "updated");
        }
        
        
        
        
        //
        
        
        int i=1;
        DefaultTableModel dtmS = (DefaultTableModel) torders.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tinfo.getModel();
        ArrayList<Order> itemS = OrderDao.getAllorders();
        Iterator<Order> itrS = itemS.iterator();
        String lid="";
        
        int rc=dtmS.getRowCount();
        for(int x=0;x<rc;x++){
            dtmS.removeRow(0);
        }
         rc=dtm.getRowCount();
        for(int x=0;x<rc;x++){
            dtm.removeRow(0);
        }
        
        
         while(itrS.hasNext()){
            Order o = itrS.next();
            dtmS.addRow(new Object[]{i,o.getOrder_id(),o.getItem_name(),o.getPrice(),o.getQuantity(),o.getEmail(),o.getDate(),o.getStatus()});
             i++;
             
             if(!o.getOrder_id().equals(lid)){
                 lid=o.getOrder_id();
                 dtm.addRow(new Object[]{o.getOrder_id(),o.getTotalsum(),o.getOfferid(),o.getCupponid()});
             }
         
         }
        
        
        
    }//GEN-LAST:event_tordersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOrderTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem nback;
    private javax.swing.JTable tinfo;
    private javax.swing.JTable torders;
    // End of variables declaration//GEN-END:variables
}
