/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import dao.CouponDao;
import dao.OfferDao;
import dao.OrderDao;
import dao.UserDao;
import java.awt.event.MouseEvent;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Offer;
import model.Coupon;
import model.*;
import model.UserCart;

/**
 *
 * @author ASUS
 */
public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    private ArrayList<UserCart> usercart=new ArrayList();
    private ArrayList<Coupon> cuppons = CouponDao.getAllCuppon();
    private Offer offer=OfferDao.getAllOffer();
    
    
    private String email;
    //constructor
    public Cart() {
        initComponents();
         if(usercart.isEmpty()){
            btnplaceorder.setEnabled(false);
        }
         
        lOfferapplied.setVisible(false);
        
        
    }
     public Cart(String email,ArrayList<UserCart> usercart) {
         this.email=email;
        this.usercart.addAll(usercart);
        initComponents();
        if(usercart.isEmpty()){
            btnplaceorder.setEnabled(false);
        }
        lOfferapplied.setVisible(false);
    }
     
    //functions
    
    private Coupon getcupponbyname(String name){
        Coupon c=new Coupon();
        
        Iterator<Coupon> itr = cuppons.iterator();
        while(itr.hasNext()){
            Coupon lc = itr.next();
            if(lc.getId().equals(name)){
                return lc;
            }
        }
        
        JOptionPane.showMessageDialog(null, "wrong cuppon entered");
        return c;
        
    }
     private void showPopUp(MouseEvent e){
        popupmenu.show(this,e.getX(), e.getY());
        
    }
     private void setSum(){
         DefaultTableModel dtm=(DefaultTableModel) tCart.getModel();
         int rc=dtm.getRowCount();
         int sum=0;
         for(int i=0;i<rc;i++){
             int s = (Integer) dtm.getValueAt(i, 4);
             sum+=s;
             
             
         }
         txtSum.setText(String.valueOf(sum));
     }
     
     private void setTable(){
         DefaultTableModel dtm = (DefaultTableModel) tCart.getModel();
          Iterator<UserCart> itr = usercart.iterator();
        int i=1;
        int cr=dtm.getRowCount();
        for(int j=0;j<cr;j++){
            dtm.removeRow(0);
        }
        while(itr.hasNext()){
            
            UserCart c =  itr.next();
            //
            System.out.println(c.getItem().getName());
            if(!c.getQty().equals("0")){
                 dtm.addRow(new Object[]{i,c.getItem().getName(),c.getQty(),c.getItem().getPrice(),Integer.parseInt(c.getItem().getPrice())*Integer.parseInt(c.getQty())});
                 i++;
            }else{
                itr.remove();
            }
           
            
        }
        setSum();
         
     }
     private void setoffer(){
        
        //
//         txtSum.setText("1000");
        //
        String ot =   txtSum.getText();
        
        
        Double sum=Double.parseDouble(txtSum.getText());
        Double per=Double.parseDouble(offer.getPercent());
        
        if(!offer.getId().equals("") && sum>100){
            
            
         sum=sum-(sum*per)/100;
            
         txtSum.setText(String.valueOf(sum));
         lOfferapplied.setVisible(true);
         lOfferapplied.setText("Offer applied !!");
         lOfferid.setText("offer id:"+offer.getId());
         lOfferid1.setText("old total :"+ot);
         lOfferid2.setText("discout : "+offer.getPercent()+"%");
        
        
        }else{
            lOfferapplied.setText("");
            lOfferid.setText("");
            lOfferid1.setText("");
            lOfferid2.setText("");
                    
        }
        if(sum<150){
            btnapply.setEnabled(false);
        }else{
            btnapply.setEnabled(true);
        }
       
        txtCuppon.setEditable(true);
         txtCuppon.setText("");
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupmenu = new javax.swing.JPopupMenu();
        mbtnprofile = new javax.swing.JMenuItem();
        mbtnhome = new javax.swing.JMenuItem();
        mbtnlogout = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCart = new javax.swing.JTable();
        subtotal = new javax.swing.JLabel();
        rs = new javax.swing.JLabel();
        dining = new javax.swing.JLabel();
        packing = new javax.swing.JLabel();
        btnplaceorder = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtCuppon = new javax.swing.JTextField();
        btnapply = new javax.swing.JButton();
        txtSum = new javax.swing.JTextField();
        lOfferapplied = new javax.swing.JLabel();
        lOfferid = new javax.swing.JLabel();
        lOfferid1 = new javax.swing.JLabel();
        lOfferid2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tCuppons = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mhome = new javax.swing.JMenuItem();

        popupmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        popupmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popupmenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                popupmenuMouseReleased(evt);
            }
        });

        mbtnprofile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mbtnprofile.setForeground(new java.awt.Color(204, 153, 0));
        mbtnprofile.setText("Profile");
        mbtnprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnprofileActionPerformed(evt);
            }
        });
        popupmenu.add(mbtnprofile);

        mbtnhome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mbtnhome.setForeground(new java.awt.Color(204, 153, 0));
        mbtnhome.setText("Home");
        mbtnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnhomeActionPerformed(evt);
            }
        });
        popupmenu.add(mbtnhome);

        mbtnlogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mbtnlogout.setForeground(new java.awt.Color(204, 153, 0));
        mbtnlogout.setText("Logout");
        mbtnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnlogoutActionPerformed(evt);
            }
        });
        popupmenu.add(mbtnlogout);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MY CART");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 169, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 20, 109, 110));

        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, 160));

        tCart.setAutoCreateRowSorter(true);
        tCart.setBackground(new java.awt.Color(255, 153, 102));
        tCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tCart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tCart.setForeground(new java.awt.Color(129, 102, 132));
        tCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Items", "Quantity", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tCart.setGridColor(new java.awt.Color(153, 102, 0));
        tCart.setSelectionBackground(new java.awt.Color(204, 102, 0));
        tCart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCartKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCartKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tCart);
        if (tCart.getColumnModel().getColumnCount() > 0) {
            tCart.getColumnModel().getColumn(0).setMinWidth(100);
            tCart.getColumnModel().getColumn(0).setPreferredWidth(100);
            tCart.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 630, 350));

        subtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subtotal.setForeground(new java.awt.Color(255, 255, 255));
        subtotal.setText("Total Amount:");
        getContentPane().add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 110, 31));

        rs.setBackground(new java.awt.Color(255, 255, 255));
        rs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rs.setForeground(new java.awt.Color(255, 255, 255));
        rs.setText("Rs");
        getContentPane().add(rs, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, 20, 30));

        dining.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dining.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foodready.jpeg"))); // NOI18N
        getContentPane().add(dining, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 40, -1));

        packing.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        packing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/packing.jpg"))); // NOI18N
        getContentPane().add(packing, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 40, -1));

        btnplaceorder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnplaceorder.setForeground(new java.awt.Color(255, 0, 102));
        btnplaceorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        btnplaceorder.setText("Place Order");
        btnplaceorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaceorderActionPerformed(evt);
            }
        });
        getContentPane().add(btnplaceorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Packing");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 98, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Dining");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 98, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apply Coupon :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 120, 30));
        getContentPane().add(txtCuppon, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, 300, 30));

        btnapply.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnapply.setForeground(new java.awt.Color(153, 0, 51));
        btnapply.setText("Apply ");
        btnapply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapplyActionPerformed(evt);
            }
        });
        getContentPane().add(btnapply, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, -1, -1));

        txtSum.setEditable(false);
        txtSum.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 270, 30));

        lOfferapplied.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lOfferapplied.setForeground(new java.awt.Color(51, 204, 0));
        lOfferapplied.setText("OFFER APPLIED!! :");
        lOfferapplied.setOpaque(true);
        getContentPane().add(lOfferapplied, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 180, 220, 40));

        lOfferid.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lOfferid.setForeground(new java.awt.Color(51, 204, 0));
        lOfferid.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lOfferid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 220, 240, 50));

        lOfferid1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lOfferid1.setForeground(new java.awt.Color(51, 204, 0));
        lOfferid1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lOfferid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 270, 240, 50));

        lOfferid2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lOfferid2.setForeground(new java.awt.Color(51, 204, 0));
        lOfferid2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lOfferid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 320, 240, 50));

        tCuppons.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tCuppons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuppons", "Rs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tCuppons.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tCuppons);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backg.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("^");
        jMenu1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N

        mhome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mhome.setForeground(new java.awt.Color(204, 153, 0));
        mhome.setText("Home");
        mhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhomeActionPerformed(evt);
            }
        });
        jMenu1.add(mhome);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popupmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupmenuMousePressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_popupmenuMousePressed

    private void popupmenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupmenuMouseReleased
        // TODO add your handling code here:
         
    }//GEN-LAST:event_popupmenuMouseReleased

    private void mhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhomeActionPerformed
        // TODO add your handling code here:
         HomePage hForm = new HomePage(email,usercart);
                hForm.setVisible(true);
                dispose(); 
    }//GEN-LAST:event_mhomeActionPerformed

    private void mbtnprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnprofileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbtnprofileActionPerformed

    private void mbtnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnhomeActionPerformed
        // TODO add your handling code here:
        HomePage hForm = new HomePage();
                hForm.setVisible(true);
                dispose(); 
    }//GEN-LAST:event_mbtnhomeActionPerformed

    private void mbtnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnlogoutActionPerformed
        // TODO add your handling code here:
        User_Login loginForm = new User_Login();
                loginForm.setVisible(true);
                dispose(); 
    }//GEN-LAST:event_mbtnlogoutActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            showPopUp(evt);}
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            showPopUp(evt);}
    }//GEN-LAST:event_formMouseReleased

    private void btnplaceorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaceorderActionPerformed
        // TODO add your handling code here:
        String preference="";
        if(jRadioButton1.isSelected()){
            preference=jRadioButton1.getText();
        }else{
            preference=jRadioButton2.getText();
        }
        int a =JOptionPane.showConfirmDialog(null,"Do you really want to place the order","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            OrderDao.saveOrder(email, usercart,txtCuppon.getText(),txtSum.getText(),offer.getId(),preference);
            JOptionPane.showMessageDialog(null, "order placed");
            //
            Order order = new Order();
            User user = UserDao.getUser(email);
            int billid = Integer.parseInt(OrderDao.getid());
            billid=billid-1;
            String bi = String.valueOf(billid);
            
            
            String path ="D:\\";
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try{
                PdfWriter.getInstance(doc, new FileOutputStream(path + ""+bi+".pdf"));
                doc.open();
                Paragraph cafeName = new Paragraph("            Cafe SMVDU        ");
                doc.add(cafeName);
                Paragraph starLine = new Paragraph("***********************************");
                doc.add(starLine);
                Paragraph para3 = new Paragraph("\tBill ID : "+bi+"\nCustomer name : "+user.getName()+"Total paid: "+txtSum.getText());
                doc.add(para3);
                doc.add(starLine);
                PdfPTable tb1 = new PdfPTable(4);
                tb1.addCell("name");
                tb1.addCell("Price");
                tb1.addCell("Quantity");
                tb1.addCell("Total");
                
                for(int i=0;i<tCart.getRowCount();i++){
                    String n = tCart.getValueAt(i, 0).toString();
                    String d = tCart.getValueAt(i, 1).toString();
                    String r = tCart.getValueAt(i, 2).toString();
                    String t = tCart.getValueAt(i, 3).toString();
                    tb1.addCell(n);
                    tb1.addCell(d);
                    tb1.addCell(r);
                    tb1.addCell(t);
                }
                doc.add(tb1);
                doc.add(starLine);
                Paragraph tmsg = new Paragraph("Thank You!");
                doc.add(tmsg);
                //open pdf
                OpenPdf.openById(bi);
                
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            doc.close();
            
            
            
            //
            usercart.clear();
            setTable();
            btnplaceorder.setEnabled(false);
            
            lOfferapplied.setEnabled(false);
            lOfferapplied.setText("");
            lOfferid.setEnabled(false);
            lOfferid.setText("");
            lOfferid1.setEnabled(false);
            lOfferid1.setText("");
            lOfferid2.setEnabled(false);
            lOfferid2.setText("");
            
            
        }
        
    }//GEN-LAST:event_btnplaceorderActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm =(DefaultTableModel) tCart.getModel();
        
//        System.out.println(usercart.size());
        
        Iterator<UserCart> itr = usercart.iterator();
        int i=1;
        while(itr.hasNext()){
            
            UserCart c =  itr.next();
            //S
//            System.out.println(c.getItem().getName());
            dtm.addRow(new Object[]{i,c.getItem().getName(),c.getQty(),c.getItem().getPrice(),Integer.parseInt(c.getItem().getPrice())*Integer.parseInt(c.getQty())});
            i++;
            
        }
//     cuppons shown 
//       cuppons.addAll(CupponDao.getAllCuppon());
//       System.out.println(cuppons.size());
//       System.out.println(cuppons.get(0).getId());
       //
       
       DefaultTableModel dtmc=(DefaultTableModel) tCuppons.getModel();
       Iterator<Coupon> itrc = cuppons.iterator();
       while(itrc.hasNext()){
           Coupon c=itrc.next();
           dtmc.addRow(new Object[]{c.getId(),c.getAmount()});
       }
       
       
//        
        
        
        setSum();
        setoffer();
        
        Double sum = Double.parseDouble(txtSum.getText());
        if(sum<150){
            btnapply.setEnabled(false);
        }else{
            btnapply.setEnabled(true);
        }
       
        
    }//GEN-LAST:event_formComponentShown

    private void tCartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCartKeyPressed
        // TODO add your handling code here:
        int ind = tCart.getSelectedRow();
        TableModel tm = tCart.getModel();
        
        String q = tm.getValueAt(ind,2).toString();
        
        int qt=Integer.parseInt(q);
        if(qt<=0){
            q="0";
        }
        
        
        UserCart nu = usercart.get(ind);
        nu.setQty(q);
        
        usercart.set(ind,nu );
        setTable();
        
        setoffer();
        
    }//GEN-LAST:event_tCartKeyPressed

    private void tCartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCartKeyReleased
        // TODO add your handling code here:
        int ind = tCart.getSelectedRow();
        TableModel tm = tCart.getModel();
        
        String q = tm.getValueAt(ind,2).toString();
        
        int qt=Integer.parseInt(q);
        if(qt<=0){
            q="0";
        }
        
        
        UserCart nu = usercart.get(ind);
        nu.setQty(q);
        
        usercart.set(ind,nu );
        setTable();
        
        setoffer();
    }//GEN-LAST:event_tCartKeyReleased

    private void btnapplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapplyActionPerformed
        // TODO add your handling code here:
        Coupon cuppon = getcupponbyname(txtCuppon.getText());
        if(!cuppon.getId().equals("")){
            Double num = Double.parseDouble(cuppon.getAmount());
            Double sum = Double.parseDouble(txtSum.getText());
            sum=sum-num;
            txtSum.setText(String.valueOf(sum));
            
            btnapply.setEnabled(false);
            txtCuppon.setEditable(false);
        }
        
    }//GEN-LAST:event_btnapplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnapply;
    private javax.swing.JButton btnplaceorder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dining;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lOfferapplied;
    private javax.swing.JLabel lOfferid;
    private javax.swing.JLabel lOfferid1;
    private javax.swing.JLabel lOfferid2;
    private javax.swing.JMenuItem mbtnhome;
    private javax.swing.JMenuItem mbtnlogout;
    private javax.swing.JMenuItem mbtnprofile;
    private javax.swing.JMenuItem mhome;
    private javax.swing.JLabel packing;
    private javax.swing.JPopupMenu popupmenu;
    private javax.swing.JLabel rs;
    private javax.swing.JLabel subtotal;
    private javax.swing.JTable tCart;
    private javax.swing.JTable tCuppons;
    private javax.swing.JTextField txtCuppon;
    private javax.swing.JTextField txtSum;
    // End of variables declaration//GEN-END:variables
}
